### ISSUE TITLE
Bug in playerctl status return 0 when fail

### ISSUE THREAD

**Issue by ArthurGorgonio** [acrisci/playerctl#126]
when I run ``` $ playerctl status ``` while spotify power off I got the message ``` No players found ```.

so I run ``` $ echo $? ``` to know the status of the last command and it returns 0

P.S. In past the status when I execute this sequence was 1

in detail
![Screenshot_20190309_223936](https://user-images.githubusercontent.com/21360791/54079840-1cc15900-42c3-11e9-9853-c5dbedceda09.png)

**Comment by acrisci** [comment]
Yeah I need to make some tests for this.

**Comment by hedgehog1029** [comment]
not quite sure when this behavior changed, but it did also break a script of mine. it seems weird because this only broke recently, and the history of the [`playerctl-cli.c`](https://github.com/acrisci/playerctl/blob/master/playerctl/playerctl-cli.c) file shows no changes to that particular method this year. dunno if this is just Arch package cycle or what

**Comment by acrisci** [comment]
I accidentally broke some subtle things in 2.0 because it was a big rewrite but I will change this back to what it was soon and do a release.
