### ISSUE TITLE
radiotray

### ISSUE THREAD

**Issue by cyril95** [acrisci/playerctl#13]
Hi, thanks for this great and proper software. Could you please add the support on "radiotray"?
Ty

**Comment by acrisci** [comment]
Currently, this project only supports the latest version of [mpris](http://specifications.freedesktop.org/mpris-spec/latest/), while radiotray supports an older version.

Tell them you want the latest mpris support to work with playerctl by commenting on [this issue](https://bitbucket.org/carlmig/radio-tray/issue/78/update-mpris-support-to-version-21).

I don't want to support an earlier version of mpris because it is out of date, and I expect everyone should be updating soon.
